### ISSUE TITLE
include more output from PTD2root and Things2Root 

### ISSUE THREAD

**Issue by MHoballah** [SuperNEMO-DBD/SensitivityModule#35]
Add a branch like 
hit of the particle on the calorimeter wall (OM number) 
tracker layers

**Comment by cherylepatrick** [comment]
I think it's a good idea Malak, you can go ahead and add it. Hamzah is a good person to speak to as he must have already done most of the processing to do the adjacent call hits. I think we already have vectors for which wall the individual hits are on so I recommend you add a vector for hit column and hit row in the same way (make sure they are done in the same order as the check of which wall - so that e.g. calo_wall[1] matches with the same hit as calo_row[1] and calo_column[1]
Does that make sense? Tagging you and Hamzah (in a consultant role!) to take a lead on getting it into SM and testing it. Thanks!

**Comment by drbenmorgan** [comment]
Closing - we'll address once SensitivityModule is integrated into Falaise (where we'll also get PTD2Root integrated properly)
