### ISSUE TITLE
flreconstruct doesn't work using the sensitivity module pipeline

### ISSUE THREAD

**Issue by HanFangXie** [SuperNEMO-DBD/SensitivityModule#8]
I was trying to use the flreconstruct with the SensitivityModule pipeline and it gave me this error:
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180112-10322-1ku3r8b/Bayeux-Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180112-10322-1ku3r8b/Bayeux-Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
[notice:void datatools::library_loader::init():450] Automatic loading of library 'SensitivityModule'...
[error:int datatools::library_loader::load(const string&, const string&, const string&, const string&, const string&):278] datatools::library_loader::load: The 'SensitivityModule' library was not loaded ! DATATOOLS_SYS_NAMESPACE says: '/home/fang/BiBKG/Sensitivity/SensitivityModule-build/libSensitivityModule.so: undefined symbol: _ZTV8TVector3' !
flreconstruct : Setup/run of simulation threw exception
[void datatools::library_loader::init():454: Automatic loading of library='SensitivityModule' failed !]

**Comment by cherylepatrick** [comment]
@lecdawson Do you recognise this message? @HanFangXie what OS/Falaise/ROOT versions are you using? SensitivityModule works fine for me on Mac and I have used it (but not the most recent version) many times on CentOS.

**Comment by cherylepatrick** [comment]
See [issue #72](https://github.com/SuperNEMO-DBD/Falaise/issues/72) for Falaise - is this the same thing?

**Comment by drbenmorgan** [comment]
Yep, same thing - the issue is a missing link to ROOT's libPhysics library, which supplies TVector3. The resolution is to explicitly link to that library. A suitable CMake script to do this on all platforms is:

``` cmake
cmake_minimum_required(VERSION 3.3)
project(SensitivityModule)
find_package(Falaise REQUIRED)

# Build a dynamic library from our sources
add_library(SensitivityModule SHARED SensitivityModule.h SensitivityModule.cpp)
target_link_libraries(SensitivityModule
  PUBLIC
    Falaise::FalaiseModule
    ${ROOT_Physics_LIBRARY}
    )
```

Here, `find_package(Falaise ...)` finds Falaise and configures its dependents (so ROOT is available after that call). Linking to `Falaise::FalaiseModule` ensures that the plugin is compiled against the relevant Falaise/dependents, but *does not link to any libraries as the flreconstruct program supplies these*. Because ROOT's libPhysics isn't default linked, it needs an explicit link, as do any further non-core libraries.

Using the above, it's possible to configure/build the module with (assuming a brew install):

```
$ cmake -DCMAKE_PREFIX_PATH="$(brew --prefix qt5-base);$(brew --prefix)" .
$ make
```

Try this out and see if it works, if there are still unresolved symbol errors, it's likely additional ROOT libs need linking.

**Comment by HanFangXie** [comment]
@cherylepatrick  root 6.12.04. 
falaise 3.1.1_1
mac os high sierra 10.13.2
And I think it looks like the same thing issue #72.

**Comment by HanFangXie** [comment]
@drbenmorgan Hi Ben, thanks. Unfortunately it is not working. Now it tells me "can't find package QtWidgetConfig.cmake". It was "can't find Qt5CoreConfig.cmake" before. I will follow the issue #72 to see what I can do.

**Comment by HanFangXie** [comment]
@drbenmorgan Hi Ben, thanks. I tried but unfortunatelly it is still not working.

**Comment by HanFangXie** [comment]
$ cmake -DCMAKE_PREFIX_PATH="$(brew --prefix qt5-base);$(brew --prefix)" ../SensitivityModule

This solved my problem of "can not find qt5core"
